version: 0.1

phases:
  install:
    commands:
      # - install nodejs
      - echo Installing nodejs 12...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # - install dependencies
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      # - test and build
      - echo Building...
      - npm run build
# artifacts:
#   files:
#     - "**/*"
#   discard-paths: no
#   base-directory: dist