version: 0.1

phases:
  pre_build:
    commands:
      # - install dependencies
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      # - test and build
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
